Runname: Run unit tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php:
          - '8.0'
          - '7.4'
        laravel:
          - '8.0'
        stability:
          - lowest
          - highest
        include:
          - laravel: '8.0'
            testbench: '6.0'

    name: Test Laravel ${{ matrix.laravel }} on ${{ matrix.php }} (${{ matrix.stability }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: pcov

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Configure Laravel and Laravel Testbench
        run:
          composer require
            "laravel/framework:${{ matrix.laravel }}"
            "orchestra/testbench:${{ matrix.testbench }}"
            --no-interaction
            --no-update

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@^1.1
        with:
          dependency-versions: ${{ matrix.stability }}

      - name: Execute tests
        run: vendor/bin/phpunit
